change_type: enhancement

component: config

note: add OTEL_INJECTOR_CONFIG_FILE to set config file location

issues: [188]

subtext: |
  This adds support for a new environment variable `OTEL_INJECTOR_CONFIG_FILE` that determines from which path the
  injector's configuration file is read. If the variable is not set or empty, the configuration file is read from the
  default path `/etc/opentelemetry/otelinject.conf`.

  This is useful in environments where you want to provide a configuration file, but you do not want to make any
  assumptions about the underlying file system's structure. I.e. you want to keep all assets of the injector (injector
  binary, auto-instrumentation agents and the injector configuration) completely separate from standard OS directories
  like `/etc`.

change_logs: []
