name: Automation - Prepare Release

on:
  workflow_dispatch:
    # Determine the version number that will be assigned to the release.
    inputs:
      candidate:
        required: true
        description: Release candidate version (like 0.70.0)
permissions:
  contents: read
jobs:
  # Releasing opentelemetry-injector
  prepare-release:
    permissions:
      contents: write # required for pushing changes in prepare-release.sh
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        id: otelbot-token
        with:
          app-id: ${{ vars.OTELBOT_APP_ID }}
          private-key: ${{ secrets.OTELBOT_PRIVATE_KEY }}
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: "1.25.4"
          cache: false
      - name: Prepare release for injector
        env:
          GITHUB_TOKEN: ${{ steps.otelbot-token.outputs.token }}
          REPO: open-telemetry/opentelemetry-injector
          CANDIDATE: ${{ inputs.candidate }}
        run: ./.github/workflows/scripts/prepare-release.sh
