name: Automation - Prepare Release

on:
  workflow_dispatch:
    # Determine the version number that will be assigned to the release.
    inputs:
      candidate:
        required: true
        description: Release candidate version (like 0.70.0)
permissions:
  contents: read
jobs:
  # Releasing opentelemetry-injector
  prepare-release:
    permissions:
      contents: write # required for pushing changes in prepare-release.sh
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: otelbot-token
        with:
          app-id: ${{ vars.OTELBOT_APP_ID }}
          private-key: ${{ secrets.OTELBOT_PRIVATE_KEY }}
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: "1.25.4"
          cache: false
      - name: Prepare release for injector
        env:
          GITHUB_TOKEN: ${{ steps.otelbot-token.outputs.token }}
          REPO: open-telemetry/opentelemetry-injector
          CANDIDATE: ${{ inputs.candidate }}
        run: ./.github/workflows/scripts/prepare-release.sh
