name: Automation - Prepare Release

on:
  workflow_dispatch:
    # Determine the version number that will be assigned to the release.
    inputs:
      version:
        required: true
        description: Release version or release candidate version (like v0.70.0 or v0.70.0-20260109)
permissions:
  contents: read
jobs:
  # Releasing opentelemetry-injector
  prepare-release:
    permissions:
      contents: write # required for pushing changes in prepare-release.sh
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: otelbot-token
        with:
          app-id: ${{ vars.OTELBOT_APP_ID }}
          private-key: ${{ secrets.OTELBOT_PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: "1.25.6"
          cache: false
      - name: Prepare release for injector
        env:
          GITHUB_TOKEN: ${{ steps.otelbot-token.outputs.token }}
          REPO: open-telemetry/opentelemetry-injector
          VERSION: ${{ inputs.version }}
        run: ./.github/workflows/scripts/prepare-release.sh
